name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.2', '8.3']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer:v2
          extensions: mbstring, json, dom

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install dependencies
        run: composer update --prefer-stable --no-interaction --no-progress

      - name: Run tests (Pest)
        run: vendor/bin/pest --colors=always

      - name: Static analysis (PHPStan)
        run: vendor/bin/phpstan analyse --no-progress --memory-limit=1G
